spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
      roles: admin
server:
  port: 1111
#wanner register the eureka
eureka-server2:
  instance:
    hostname: eureka-server2
    port: 1112
eureka:
  instance:
    hostname: eureka-server1 #need to modify the hosts file
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka-server2.instance.hostname}:${eureka-server2.instance.port}/eureka/
  server:
    enable-self-preservation: false
  dashboard: #指定dashboard的地址
    enabled: true
    path: /eureka-ui  #不可以使用eureka，原因未知

