spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka-server1:
  instance:
    hostname: eureka-server1 #这个实际是eureka-server-1的IP地址
    port: 1111
#将该Eureka注册中心注册到另一个注册中心，进行相互注册形成高可用注册中心
eureka:
  instance:
    hostname: eureka-server2 #127.0.0.1或者是eureka-server-2，这个是代表该注册中心的hostname，eureka-server-2要修改hosts文件
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka-server1.instance.hostname}:${eureka-server1.instance.port}/eureka/
#  server:
#    enable-self-preservation: false
  dashboard: #指定dashboard的地址
      enabled: true
      path: /eureka-ui  #不可以使用eureka，原因未知