spring:
  application:
    name: tybest-eureka
  security:
    user:
      name: admin
      password: admin
      roles: admin
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #close eureka protect mode
    eviction-interval-timer-in-ms: 5000
    renewal-threshold-update-interval-ms: 5000
