server:
  port: 8090
spring:
  application:
    name: tybest-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jane09/tybest-cloud/config-repos
          search-paths: configs